import "server-only";

import { createHash } from "node:crypto";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import path from "node:path";

const repoRoot = process.cwd();
const migrationsDir = path.join(repoRoot, "supabase", "migrations");
const canonicalTypesFile = path.join(repoRoot, "types", "supabase-types.d.ts");
const HEADER_PATTERN =
  /^\/\/ Generated by Memory Lane db:types\. Do not edit by hand\.\n\/\/ Source mode: ([^\n]+)\n\/\/ Schema fingerprint: ([a-f0-9]+)\n\/\/ Latest migration: ([^\n]+)\n/m;

let hasWarned = false;
let cachedMessage: string | null | undefined;

function getSchemaFingerprint() {
  if (!existsSync(migrationsDir)) {
    return null;
  }

  const migrationFiles = readdirSync(migrationsDir)
    .filter((entry) => entry.endsWith(".sql"))
    .sort((left, right) => left.localeCompare(right));

  const hash = createHash("sha256");
  for (const fileName of migrationFiles) {
    hash.update(fileName);
    hash.update("\n");
    hash.update(readFileSync(path.join(migrationsDir, fileName)));
    hash.update("\n--migration-boundary--\n");
  }

  return hash.digest("hex");
}

function getMessage() {
  if (process.env.NODE_ENV === "production") {
    return null;
  }

  if (!existsSync(canonicalTypesFile)) {
    return "Supabase generated types are missing. Run `npm run db:sync`, then restart the dev server.";
  }

  const schemaFingerprint = getSchemaFingerprint();
  if (!schemaFingerprint) {
    return null;
  }

  const fileContents = readFileSync(canonicalTypesFile, "utf8").replace(/\r\n/g, "\n");
  const header = fileContents.match(HEADER_PATTERN);

  if (!header) {
    return "Supabase generated types header is missing. Run `npm run db:sync`, then restart the dev server.";
  }

  if (header[2] !== schemaFingerprint) {
    return "Supabase migrations and generated types are out of sync. Run `npm run db:sync`. If the warning stays, run `npm run clean:next` and restart the dev server.";
  }

  return null;
}

export function getDevSchemaSyncMessage() {
  if (cachedMessage === undefined) {
    cachedMessage = getMessage();
  }
  const message = cachedMessage;

  if (message && !hasWarned) {
    console.warn(`[schema-sync] ${message}`);
    hasWarned = true;
  }

  return message;
}
