export const CANONICAL_PRIVACY_PRACTICES_NOTICE = [
  "Notice of Privacy Practices",
  "MEMBER INFORMATION. MEMBER RIGHTS. OUR RESPONSIBILITIES.",
  "This notice describes how medical information about the Member may be used and disclosed and how the Member (or your health care attorney-in-fact) can get access to this information. For purposes of this notice, Member means the person attending our Center and receiving the adult day care services. Please review this Notice carefully.",
  "MEMBER RIGHTS",
  "When it comes to the Member's health information, the Member has certain rights. This section explains the Member's rights and some of our responsibilities to help the Member.",
  "GET AN ELECTRONIC OR PAPER COPY OF THE MEMBER'S MEDICAL RECORD",
  "The Member (or their attorney-in-fact) can ask to see or get an electronic or paper copy of the Member's medical record and other health information we have about the Member. Ask us how to do this.",
  "We will provide a copy or a summary of the Member's health information, usually within 30 days of the request. We may charge a reasonable, cost-based fee.",
  "ASK US TO CORRECT THE MEMBER'S MEDICAL RECORD",
  "The Member (or their attorney-in-fact) can ask us to correct health information about the Member that is incorrect or incomplete. Ask us how to do this.",
  "We may say \"no\" to the request, but we'll explain why in writing within 60 days.",
  "REQUEST CONFIDENTIAL COMMUNICATIONS",
  "The Member (or their attorney-in-fact) can ask us to contact the Member (or their attorney-in tact) in a specific way (for example, home or office phone) or to send mail to a different address.",
  "We will say \"yes\" to all reasonable requests.",
  "ASK US TO LIMIT WHAT WE USE OR SHARE",
  "The Member (or their attorney-in-fact) can ask us not to use or share certain health information for treatment, payment, or our operations. We are not required to agree to the request, and we may say \"no\" if it would affect the Member's care.",
  "If the Member or representative pays for a service or health care item out-of-pocket in full, the Member or representative can ask us not to share that information for the purpose of payment or our operations with the Member's health insurer. We will say \"yes\" unless a law requires us to share that information.",
  "GET A LIST OF THOSE WITH WHOM WE HAVE SHARED INFORMATION",
  "The Member (or their attorney-in-fact) can request a list (accounting) of the times we've shared the Member's health information for six years prior to the date requested, who we shared it with, and why.",
  "We will include all the disclosures except for those about treatment, payment, and health care operations, and certain other disclosures (such as any the Member (or their attorney-in-fact) asked us to make). We'll provide one accounting a year for free but will charge a reasonable, cost based fee if the Member (or its attorney-in-fact) requests another one within 12 months.",
  "GET A COPY OF THIS PRIVACY NOTICE",
  "The Member (or their attorney-in-fact) can ask for a paper copy of this notice at any time, even if the Member (or their attorney-in-fact) has agreed to receive the notice electronically. We will provide a paper copy promptly.",
  "CHOOSE SOMEONE TO ACT FOR THE MEMBER",
  "If the Member has given someone medical power of attorney or if someone is the Member's legal guardian, that person can exercise the Member's rights and make choices about the Member's health information.",
  "We will make sure the person has this authority and can act for the Member before we take any action.",
  "FILE A COMPLAINT IF THE MEMBER FEELS THEIR RIGHTS ARE VIOLATED",
  "The Member (or their attorney-in-fact) can complain if they feel we have violated the Member's rights by contacting us using the information on the last page of this notice.",
  "The Member (or their attorney-in-fact) can file a complaint with the South Carolina Department of Public Health, calling (888) 843-3718 or by visiting website https://apps.dhec.sc.gov/Health/GenCounselComplaints/",
  "We will not retaliate against the Member for filing a complaint.",
  "MEMBER'S CHOICES",
  "For certain health information, the Member (or their attorney-in-fact) can tell us their choices about what we share. If the Member (or their attorney-in-fact) has a clear preference for how we share the information in the situations described below, talk to us. Provide the instructions and we will follow the instructions.",
  "In these cases, the Member (or their attorney-in-fact) has both the right and choice to tell us to:",
  "Share information with the family, close friends, or others involved in the care",
  "Share information in a disaster relief situation",
  "Include the Member's information in a hospital directory",
  "If the Member (or its attorney-in-fact) is not able to tell us the preference, for example if the Member is unconscious, we may share their information if we believe it is in the Member's best interest. We may also share the Member's information when needed to lessen a serious and imminent threat to health or safety.",
  "In these cases, we never share the Member's information unless the Member (or their attorney-in-fact) gives us written permission:",
  "Marketing purposes",
  "Sale of the Member's information",
  "Most sharing of psychotherapy notes",
  "In the case of fundraising:",
  "We may contact the Member (or their attorney-in-fact) for fundraising efforts, but the Member (or their attorney-in-fact) can tell us not to contact them again.",
  "OUR USES & DISCLOSURES",
  "How do we typically use or share the Member's health information?",
  "We typically use or share the Member's health information in the following ways:",
  "TO TREAT THE MEMBER",
  "We can use the Member's health information and share it with other professionals who are treating the Member. Example: A doctor treating the Member for an injury asks another doctor about the Member's overall health condition.",
  "TO RUN OUR ORGANIZATION",
  "We can use and share the Member's health information to run our organization, improve the Member's care, and contact the Member (or their attorney-in-fact) when necessary. Example: We use health information about the Member to manage their treatment and services.",
  "TO BILL FOR SERVICES",
  "We can use and share the Member's health information to bill and get payment from health plans or other entities. Example: We give information about the Member to the Member's health insurance plan so it will pay for the services.",
  "How else can we use or share the Member's health information?",
  "We are allowed or required to share the Member's information in other ways - usually in ways that contribute to the public good, such as public health and research. We have to meet many conditions in the law before we can share the Member's information for these purposes. For more information see: www.hhs.gov/ocr/privacy/hipaa/understanding/consumers/index.html.",
  "PUBLIC HEALTH & SAFETY ISSUES",
  "We can share health information about the Member's for certain situations such as:",
  "Preventing disease",
  "Helping with product recalls",
  "Reporting adverse reactions to medications",
  "Reporting suspected abuse, neglect, or domestic violence",
  "Preventing or reducing a serious threat to anyone's health or safety",
  "Do Research",
  "We can use or share the Member's information for health research.",
  "COMPLY WITH THE LAW",
  "We will share information about the Member if state or federal laws require it, including with the Department of Health and Human Services if it wants to see that we're complying with federal privacy law.",
  "RESPOND TO ORGAN & TISSUE DONATION REQUESTS",
  "We can share health information about the Member with organ procurement organizations.",
  "WORK WITH A MEDICAL EXAMINER OR FUNERAL DIRECTOR",
  "We can share health information with a coroner, medical examiner, or funeral director when an individual dies.",
  "ADDRESS WORKERS' COMPENSATION, LAW ENFORCEMENT, & OTHER GOVERNMENT REQUESTS",
  "We can use or share health information about the Member:",
  "For workers' compensation claims",
  "For law enforcement purposes or with a law enforcement official",
  "With health oversight agencies for activities authorized by law",
  "For special government functions such as military, national security, and presidential protective services",
  "RESPOND TO LAWSUITS & LEGAL ACTIONS",
  "We can share health information about the Member in response to a court or administrative order, or in response to a subpoena.",
  "OUR RESPONSIBILITIES",
  "We are required by law to maintain the privacy and security of the Member's protected health information.",
  "We will let the Member (or their attorney-in-fact) know promptly if a breach occurs that may have compromised the privacy or security of the Member's information.",
  "We must follow the duties and privacy practices described in this notice and give the Member (or their attorney-in-fact) a copy of it.",
  "We will not use or share the Member's information other than as described here unless the Member (or their attorney-in-fact) tells us we can in writing. If the Member (or their attorney-in-fact) tell us we can, the Member (or their attorney-in-fact) may change their mind at any time. Let us know in writing if the Member (or their attorney-in-fact) change your mind.",
  "For more information see: www.hhs.gov/ocr/privacy/hipaa/understanding/consumers/noticepp.html.",
  "CHANGES TO THE TERMS OF THIS NOTICE",
  "We can change the terms of this notice, and the changes will apply to all information we have about the Member. The new notice will be available upon request, in our office, and on our website.",
  "OTHER INSTRUCTIONS FOR NOTICE",
  "This Notice is effective as of 10/1/2024.",
  "CENTER CONTACT",
  "Michelle Piscatelli, Center Director",
  "803-591-9898",
  "Email: mpiscatelli@townsquare.net",
  "Town Square Fort Mill",
  "368 Fort Mill Parkway, Fort Mill, SC 29715",
  "Responsible Party/Guarantor Acknowledgement: __________________________________________ Date __________"
] as const;

export const CANONICAL_STATEMENT_OF_RIGHTS_NOTICE = [
  "Statement of Rights of Adult Day Care Participants",
  "Each Participant must be accorded the following rights:",
  "The right to be treated as an Adult, with consideration, respect, and dignity, including privacy in treatment and in care for personal needs;",
  "The right to participate in a program of services and activities designed to encourage independence, learning, growth, and awareness of constructive ways to develop one’s interests and talents;",
  "The right to self-determination within the day care setting, including the opportunity to:",
  "Participate in developing one’s plan for services and any changes therein;",
  "Decide whether to participate in any given activity;",
  "Be involved to the extent possible in program planning and operation;",
  "Refuse treatment, if applicable, and be informed of the consequences of such refusal; and",
  "End participation in the Facility any time;",
  "The right to be cared about in an atmosphere of sincere interest and concern in which needed support and services are provided;",
  "The right to a safe, secure, and clean environment;",
  "The right to confidentiality and the requirement for written consent for release of information to persons not authorized under law to receive it;",
  "The right to voice grievances without discrimination or reprisal with respect to care or treatment, if applicable, that is or is not provided;",
  "The right to be fully informed, as evidenced by the Participant’s written acknowledgment of these rights, of all rules and regulations regarding Participant conduct and responsibilities;",
  "The right to be free from Harm, Exploitation, Abuse, or Neglect;",
  "The right to be fully informed, at the time of enrollment, of services and activities available and related charges;",
  "The right to communicate with others and be understood by them to the extent of the Participant’s capability.",
  "The Facility shall provide grievance and complaint procedures for Participants, Sponsors, and Responsible Parties on the Statement of Rights of Adult Day Care Participants to be exercised on behalf of the Participants to enforce the Statement of Rights of Adult Day Care Participants that includes the Department’s email address and telephone number. To voice grievances or file a complaint regarding care or treatment, you, your sponsor, or designated representative may do so without fear of retaliation. You may file a complaint with the South Carolina Department of Health and Environmental Control (DHEC) using:",
  "Phone: (803) 5454370 or Tollfree: 18009226735",
  "Online: Submit a health facility complaint form via the DHEC website",
  "_____________________________________________________________________",
  "Member representative/Guarantor acknowledgement Date"
] as const;

export const CANONICAL_PHOTO_CONSENT_NOTICE = [
  "AUTHORIZATION FOR USE OF IMAGE, VOICE, PERFORMANCE OR LIKENESS",
  "I do____do not___ permit and authorize Town Square Franchising, LLC. and its affiliates and its employees, agents, and personnel who are acting on behalf of the Town Square Franchising, LLC (collectively the “Company”) to use my name, photograph, video, sound/voice recording or other likeness for publicity, marketing, training, and promotion of the Company without compensation to me. I understand my name, photograph, video, sound/voice recording or other likeness may be copied and distributed by means of various media, including, but not limited to, publications, video, television broadcasts/rebroadcasts, radio transmissions/retransmissions, news releases, websites, brochures, billboards or signs. I acknowledge that the Company has the right to make one or more photographs, audio recordings, videotape or disk presentations, or other electronic reproductions of my image, voice or performance in accordance with this agreement. I waive any right to inspect or approve the finished product, or any material in which the Company may eventually use.",
  "I relinquish and give the Company all rights, title, and interests in and to the photograph, video, sound/voice recording or other likeness including any copyright therein. This consent and release shall be binding upon my heirs, successors, assigns, and legal representations.",
  "I understand that, although the Company will attempt to use my name, photograph, video, sound/voice recording or other likeness in accordance with standards of good judgment, the Company cannot warrant or guarantee that any further dissemination of my name, photograph, video, sound/voice recording or other likeness will be subject to Company supervision or control. Accordingly, I release the Company from any and all liability related to dissemination of my photograph of my name, photograph, video, sound/voice recording or other likeness, reproduction, distribution, and display in print or any and all other media, and any alteration, distortion or illusionary effect, whether intentional or otherwise, in connection with said use, including, but not limited to claims of libel, slander, or invasion of privacy. I also understand that I may not withdraw my permission for the use of any photos or other likeness at any time in the future.",
  "I have read and understand the conditions of this consent form.",
  "Responsible Party/Guarantor: ____________________________ Date ____________",
  "Member Name: ______________________________________"
] as const;

export const CANONICAL_ANCILLARY_CHARGES_NOTICE = [
  "Ancillary Charges Notice",
  "Hello, Town Square Families!",
  "We would like to inform you of some minor ancillary charges that we have deemed necessary due to the cost of supplies and labor.",
  "Effective, October 1, 2024, the following fees will be implemented for ancillary services below:",
  "Member Soiled Laundry: $5.00",
  "Disposable Briefs: $5.00 each",
  "Insulin Supplies: $5.00 per use",
  "Shower: $25.00",
  "Late Pick-up: $25 for the first 15 minutes, and $2.00/minute thereafter (not to exceed 30 minutes)",
  "It is important to note that if you are more than 60 minutes late to pick up your loved one, we are mandated to call 911 due to abandonment. We understand that emergencies can occur, therefore please communicate with us, regarding delays.",
  "If you would like to add any of the ancillary services mentioned above, please let us know and we will ensure to add the cost to your monthly invoice.",
  "Thank you for your understanding and cooperation. If you have any questions or concerns, please don't hesitate to reach out to us.",
  "Sincerely,",
  "Town Square Management",
  "Responsible Party/Guarantor: ____________________________ Date ____________",
  "Member Name: ______________________________________"
] as const;
