export const ENROLLMENT_PACKET_LEGAL_TEXT = {
  membershipAgreement: [
    "This Membership Agreement is entered into by and between Town Square Fort Mill located at 368 Fort Mill Parkway, Suite 106, Fort Mill, SC 29715 and the Member and Responsible Party.",
    "Services: Town Square shall provide adult day care and support services to Member at its Town Square facility at the address above (the Center). The adult day care and support services that are available to the Member include, assistance with activities of daily living, education programs, physical activities, health monitoring, social activities, preparation of meals/snacks, and coordination of transportation services.",
    "Extra Services are available outside the basic daily charge. To take advantage of either of these services, please contact the Town Square Director. A working barber/hair salon offers several ancillary services for an additional fee. Shower Assistance: Town Square also understands that showers may become harder to manage at home, and we can help provide shower assistance for an additional $25 fee.",
    "Fees: Member shall pay the applicable fees as provided on Exhibit A, which is attached and incorporated by reference, at the time of enrollment and then thereafter on a monthly basis. This is payable by the first of the month. Fees shall be paid by ACH direct debit of Member's assigned bank account. Accounts not paid within terms are subject to a 1.5% per invoice finance charge plus attorney's fees and costs of collection.",
    "The first payment will include the non-refundable center fee and the daily rate for the upcoming month of attendance. Moving forward, the member will be billed on the first business day of the month for all scheduled attendance days for the upcoming month. Any additional days attended will be added to the next month's invoice. Invoices will be issued on/about the 25th of every month for the following month. Accounts will be auto drafted on/about the 1st of every month for the present month.",
    "Payment made by credit card for the initial charges are subject to a 3% fee, otherwise a check will be accepted for this payment. The member will be unable to attend the Town Square Center until all past balances are collected. Should any fee need to change the center will provide a 30-day written notice.",
    "Scheduling: Member or their representative shall schedule the dates and times that they will be attending the Center. The schedule shall be selected on the Enrollment Form. If Member is unable to attend a scheduled day for a foreseeable absence, the Member or their representative must notify the Center 2 days in advance. If less notice is given, the center will bill for the day (up to a scheduled week) but allow make-up days to be used within that same month.",
    "Please refer to the Welcome Guide regarding holiday closings and weather closings. Should the center close due to inclement weather, the member shall not be billed for that day.",
    "Emergencies: In the event of an emergency, personnel of the Center are authorized to take such measures for the Member's welfare as may be professionally appropriate, including transfer to an emergency center. The Center will make all efforts to honor hospital preference but not guarantee.",
    "Members' Responsibilities: Member will remain under the care of a Healthcare Practitioner while enrolled in Town Square. Should a member change their Healthcare Practitioner the Center will be notified of the change, within 7 days. The Member or Responsible Party will also report to the Center Nurse any changes in medication, treatments, surgery, hospitalizations, ER visits, urgent medical care, falls, etc. If the member is hospitalized, discharge paperwork is required to resume attendance.",
    "Termination of Membership: Town Square, in its sole discretion, may terminate a member's membership if a member is deemed medically or behaviorally inappropriate. Town Square will formulate a discharge plan, including at least a 30-day written notice to the Member or the Member's Responsible Party.",
    "Notice of Privacy Practices: The Notice of Privacy Practices provides information about how Town Square may use and disclose protected health information about the Member. By signing this Agreement, the Member consents to Town Square's use and disclosure of protected health information about Member for purposes of treatment, payment and health care operations.",
    "Use of Photography/Video: Member permits and authorizes Town Square to use photographs or video of themselves while in attendance of the Center for publicity, marketing, training, and promotion of Town Square.",
    "Binding Arbitration: Member agrees to binding arbitration pursuant to the commercial arbitration rules of the American Arbitration Association as the exclusive means to resolve all disputes arising from or related to this Agreement, with the exception of a Member's failure to pay fees or other amounts owed to Town Square for which Town Square may file an action in an applicable court of law to recover.",
    "By signing below, Member and Responsible Party/Guarantor acknowledge and accept the Membership Agreement terms."
  ],
  exhibitAPaymentAuthorization: [
    "Exhibit A: Payment Authorization & Fee Schedule",
    "Daily Center Fee: 1 day per week: $205 per day; 2-3 days per week: $180 per day; 4-5 days per week: $170 per day.",
    "Community Fee: due before the member's first day.",
    "Total Amount Due for Initial Enrollment: calculated by staff and shown in this packet.",
    "We are a membership-based program. Billing is processed at the beginning of each month for the upcoming month of services.",
    "Please select one payment option below: ACH (Bank Draft) or Credit Card (Auto Charge).",
    "ACH AUTHORIZATION: I hereby authorize payments for all invoices to be debited using the checking/savings account listed below. I understand that my account will be drafted on or about the 1st day of each month. If for any reason a bank draft is returned by my bank, a $25 return fee will be applied to the account plus a 2% late fee.",
    "The undersigned guarantor hereby authorizes Town Square to initiate debit entries and/or credit correction entries to the undersigned's checking and/or savings account(s) indicated below and the depository designated below (Bank) to debit or credit such account(s) pursuant to Town Square's instructions.",
    "CREDIT CARD AUTHORIZATION: I authorize Town Square to charge the credit card listed below for all membership fees and authorized services.",
    "I understand that a 3% processing surcharge will be added to all credit card transactions. My card will be charged on or about the 1st day of each month for the upcoming month of services, including the 3% surcharge. If a charge is declined, a $25 fee plus a 2% late fee may be applied.",
    "I authorize Town Square to retain this information on file and to charge the card for all recurring monthly membership fees and any additional authorized charges in accordance with the Membership Agreement."
  ],
  privacyPractices: [
    "Notice of Privacy Practices",
    "MEMBER INFORMATION. MEMBER RIGHTS. OUR RESPONSIBILITIES.",
    "This notice describes how medical information about the Member may be used and disclosed and how the Member (or your health care attorney-in-fact) can get access to this information. For purposes of this notice, Member means the person attending our Center and receiving the adult day care services. Please review this Notice carefully.",
    "MEMBER RIGHTS",
    "When it comes to the Member's health information, the Member has certain rights. This section explains the Member's rights and some of our responsibilities to help the Member.",
    "GET AN ELECTRONIC OR PAPER COPY OF THE MEMBER'S MEDICAL RECORD: The Member (or their attorney-in-fact) can ask to see or get an electronic or paper copy of the Member's medical record and other health information we have about the Member.",
    "ASK US TO CORRECT THE MEMBER'S MEDICAL RECORD: The Member (or their attorney-in-fact) can ask us to correct health information about the Member that is incorrect or incomplete.",
    "REQUEST CONFIDENTIAL COMMUNICATIONS: The Member (or their attorney-in-fact) can ask us to contact the Member (or their attorney-in-fact) in a specific way or to send mail to a different address.",
    "ASK US TO LIMIT WHAT WE USE OR SHARE: The Member (or their attorney-in-fact) can ask us not to use or share certain health information for treatment, payment, or our operations.",
    "GET A LIST OF THOSE WITH WHOM WE HAVE SHARED INFORMATION: The Member (or their attorney-in-fact) can request a list (accounting) of the times we've shared the Member's health information.",
    "CHOOSE SOMEONE TO ACT FOR THE MEMBER: If the Member has given someone medical power of attorney or if someone is the Member's legal guardian, that person can exercise the Member's rights and make choices about the Member's health information.",
    "FILE A COMPLAINT IF THE MEMBER FEELS THEIR RIGHTS ARE VIOLATED: The Member (or their attorney-in-fact) can complain if they feel we have violated the Member's rights.",
    "OUR USES & DISCLOSURES: We typically use or share the Member's health information to treat the Member, run our organization, and bill for services.",
    "OUR RESPONSIBILITIES: We are required by law to maintain the privacy and security of the Member's protected health information. We must follow the duties and privacy practices described in this notice.",
    "CHANGES TO THE TERMS OF THIS NOTICE: We can change the terms of this notice, and the changes will apply to all information we have about the Member.",
    "This Notice is effective as of 10/1/2024.",
    "CENTER CONTACT: Michelle Piscatelli, Center Director, 803-591-9898, mpiscatelli@townsquare.net, Town Square Fort Mill, 368 Fort Mill Parkway, Fort Mill, SC 29715."
  ],
  statementOfRights: [
    "Statement of Rights of Adult Day Care Participants",
    "Each Participant must be accorded the following rights:",
    "The right to be treated as an Adult, with consideration, respect, and dignity, including privacy in treatment and in care for personal needs.",
    "The right to participate in a program of services and activities designed to encourage independence, learning, growth, and awareness of constructive ways to develop one's interests and talents.",
    "The right to self-determination within the day care setting, including the opportunity to participate in developing one's plan for services and any changes therein; decide whether to participate in any given activity; be involved to the extent possible in program planning and operation; refuse treatment, if applicable, and be informed of the consequences of such refusal; and end participation in the Facility any time.",
    "The right to be cared about in an atmosphere of sincere interest and concern in which needed support and services are provided.",
    "The right to a safe, secure, and clean environment.",
    "The right to confidentiality and the requirement for written consent for release of information to persons not authorized under law to receive it.",
    "The right to voice grievances without discrimination or reprisal with respect to care or treatment, if applicable, that is or is not provided.",
    "The right to be fully informed, as evidenced by the Participant's written acknowledgment of these rights, of all rules and regulations regarding Participant conduct and responsibilities.",
    "The right to be free from Harm, Exploitation, Abuse, or Neglect.",
    "The right to be fully informed, at the time of enrollment, of services and activities available and related charges.",
    "The right to communicate with others and be understood by them to the extent of the Participant's capability.",
    "To voice grievances or file a complaint regarding care or treatment, you, your sponsor, or designated representative may do so without fear of retaliation. You may file a complaint with the South Carolina Department of Health and Environmental Control (DHEC)."
  ],
  photoConsent: [
    "AUTHORIZATION FOR USE OF IMAGE, VOICE, PERFORMANCE OR LIKENESS",
    "I do permit / I do not permit and authorize Town Square Franchising, LLC and its affiliates and its employees, agents, and personnel who are acting on behalf of the Company to use my name, photograph, video, sound/voice recording or other likeness for publicity, marketing, training, and promotion of the Company without compensation to me.",
    "I understand my name, photograph, video, sound/voice recording or other likeness may be copied and distributed by means of various media, including, but not limited to, publications, video, television broadcasts/rebroadcasts, radio transmissions/retransmissions, news releases, websites, brochures, billboards or signs.",
    "I acknowledge that the Company has the right to make one or more photographs, audio recordings, videotape or disk presentations, or other electronic reproductions of my image, voice or performance in accordance with this agreement. I waive any right to inspect or approve the finished product, or any material in which the Company may eventually use.",
    "I relinquish and give the Company all rights, title, and interests in and to the photograph, video, sound/voice recording or other likeness including any copyright therein. This consent and release shall be binding upon my heirs, successors, assigns, and legal representations.",
    "I understand that, although the Company will attempt to use my name, photograph, video, sound/voice recording or other likeness in accordance with standards of good judgment, the Company cannot warrant or guarantee that any further dissemination will be subject to Company supervision or control.",
    "I have read and understand the conditions of this consent form."
  ],
  ancillaryCharges: [
    "Ancillary Charges Notice",
    "Hello, Town Square Families!",
    "We would like to inform you of some minor ancillary charges that we have deemed necessary due to the cost of supplies and labor.",
    "Effective October 1, 2024, the following fees will be implemented for ancillary services below: Member Soiled Laundry: $5.00; Disposable Briefs: $5.00 each; Insulin Supplies: $5.00 per use; Shower: $25.00.",
    "Late Pick-up: $25 for the first 15 minutes, and $2.00/minute thereafter (not to exceed 30 minutes).",
    "It is important to note that if you are more than 60 minutes late to pick up your loved one, we are mandated to call 911 due to abandonment.",
    "If you would like to add any of the ancillary services mentioned above, please let us know and we will ensure to add the cost to your monthly invoice.",
    "Thank you for your understanding and cooperation. If you have any questions or concerns, please don't hesitate to reach out to us.",
    "Sincerely, Town Square Management"
  ]
} as const;
