"use strict";

const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");
const { spawnSync } = require("node:child_process");

const repoRoot = path.resolve(__dirname, "..", "..");
const migrationsDir = path.join(repoRoot, "supabase", "migrations");
const canonicalTypesFile = path.join(repoRoot, "types", "supabase-types.d.ts");
const supabaseTempDir = path.join(repoRoot, "supabase", ".temp");

function getSupabaseExecutable() {
  return process.platform === "win32" ? "supabase.cmd" : "supabase";
}

function resolveSupabaseCommand() {
  return getSupabaseExecutable();
}

function normalizeNewlines(value) {
  return String(value ?? "").replace(/\r\n/g, "\n");
}

function readTempFile(name) {
  const filePath = path.join(supabaseTempDir, name);
  if (!fs.existsSync(filePath)) {
    return null;
  }
  const value = normalizeNewlines(fs.readFileSync(filePath, "utf8")).trim();
  return value || null;
}

function getLinkedDbUrl() {
  const rawPoolerUrl = readTempFile("pooler-url");
  const password = String(process.env.SUPABASE_DB_PASSWORD ?? "").trim();
  if (!rawPoolerUrl || !password) {
    return null;
  }

  let parsed;
  try {
    parsed = new URL(rawPoolerUrl);
  } catch {
    return null;
  }

  parsed.password = password;
  if (!parsed.searchParams.has("sslmode")) {
    parsed.searchParams.set("sslmode", "require");
  }
  return parsed.toString();
}

function getMigrationFiles() {
  if (!fs.existsSync(migrationsDir)) {
    throw new Error(`Supabase migrations directory not found: ${migrationsDir}`);
  }

  return fs
    .readdirSync(migrationsDir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith(".sql"))
    .map((entry) => path.join(migrationsDir, entry.name))
    .sort((left, right) => path.basename(left).localeCompare(path.basename(right)));
}

function getSchemaMetadata() {
  const migrationFiles = getMigrationFiles();
  const hash = crypto.createHash("sha256");

  for (const filePath of migrationFiles) {
    hash.update(path.basename(filePath));
    hash.update("\n");
    hash.update(fs.readFileSync(filePath));
    hash.update("\n--migration-boundary--\n");
  }

  return {
    fingerprint: hash.digest("hex"),
    latestMigration: migrationFiles.length > 0 ? path.basename(migrationFiles[migrationFiles.length - 1]) : "none"
  };
}

function buildHeader(input) {
  return [
    "// Generated by Memory Lane db:types. Do not edit by hand.",
    `// Source mode: ${input.mode}`,
    `// Schema fingerprint: ${input.fingerprint}`,
    `// Latest migration: ${input.latestMigration}`,
    ""
  ].join("\n");
}

function normalizeGeneratedBody(body) {
  const normalized = normalizeNewlines(body).replace(/^\uFEFF/, "").trimStart();
  return normalized.endsWith("\n") ? normalized : `${normalized}\n`;
}

function buildTypesFileContent(input) {
  return `${buildHeader(input)}${normalizeGeneratedBody(input.body)}`;
}

function formatCommand(args) {
  return `${path.basename(resolveSupabaseCommand())} ${args.join(" ")}`;
}

function runSupabase(args) {
  const command = resolveSupabaseCommand();
  const result = spawnSync(command, args, {
    cwd: repoRoot,
    encoding: "utf8",
    stdio: "pipe"
  });

  if (result.error) {
    throw new Error(`Failed to run ${formatCommand(args)}: ${result.error.message}`);
  }

  return {
    status: result.status ?? 1,
    stdout: normalizeNewlines(result.stdout),
    stderr: normalizeNewlines(result.stderr)
  };
}

function formatSupabaseOutput(result) {
  return [result.stdout.trim(), result.stderr.trim()].filter(Boolean).join("\n");
}

function assertDatabaseUpToDate(mode) {
  const scopeFlag = mode === "local" ? "--local" : "--linked";
  const result = runSupabase(["db", "push", "--dry-run", scopeFlag]);
  const output = `${result.stdout}\n${result.stderr}`.toLowerCase();

  if (result.status !== 0) {
    throw new Error(
      [
        `Supabase schema check failed while running ${formatCommand(["db", "push", "--dry-run", scopeFlag])}.`,
        formatSupabaseOutput(result)
      ]
        .filter(Boolean)
        .join("\n")
    );
  }

  if (output.includes("up to date")) {
    return;
  }

  const recommendedCommand =
    mode === "local" ? "npm run db:push:local && npm run db:types:local" : "npm run db:sync";

  throw new Error(
    [
      `Supabase ${mode} database is not in sync with local migrations.`,
      `Run ${recommendedCommand} before continuing.`,
      formatSupabaseOutput(result)
    ]
      .filter(Boolean)
      .join("\n")
  );
}

function generateTypesBody(mode) {
  const linkedDbUrl = mode === "linked" ? getLinkedDbUrl() : null;
  const scopeArgs =
    mode === "local"
      ? ["--local"]
      : linkedDbUrl
        ? ["--db-url", linkedDbUrl]
        : ["--linked"];

  if (mode === "linked" && !linkedDbUrl && !String(process.env.SUPABASE_ACCESS_TOKEN ?? "").trim()) {
    throw new Error(
      [
        "Linked Supabase type generation requires either a valid SUPABASE_ACCESS_TOKEN or a linked remote pooler URL plus SUPABASE_DB_PASSWORD.",
        "Run `npx supabase login`, or set SUPABASE_DB_PASSWORD after linking the project before running db:types."
      ].join("\n")
    );
  }

  const result = runSupabase(["gen", "types", "typescript", ...scopeArgs, "--schema", "public"]);

  if (result.status !== 0) {
    throw new Error(
      [
        `Supabase type generation failed while running ${formatCommand(["gen", "types", "typescript", ...(linkedDbUrl && mode === "linked" ? ["--db-url", "<redacted>"] : scopeArgs), "--schema", "public"])}.`,
        formatSupabaseOutput(result)
      ]
        .filter(Boolean)
        .join("\n")
    );
  }

  if (!result.stdout.trim()) {
    throw new Error(`Supabase type generation returned no output for ${mode} mode.`);
  }

  return result.stdout;
}

function readCanonicalTypesFile() {
  if (!fs.existsSync(canonicalTypesFile)) {
    return null;
  }

  return normalizeNewlines(fs.readFileSync(canonicalTypesFile, "utf8"));
}

function writeCanonicalTypesFile(content) {
  fs.mkdirSync(path.dirname(canonicalTypesFile), { recursive: true });
  fs.writeFileSync(canonicalTypesFile, normalizeNewlines(content), "utf8");
}

module.exports = {
  canonicalTypesFile,
  buildHeader,
  buildTypesFileContent,
  formatSupabaseOutput,
  generateTypesBody,
  getSchemaMetadata,
  normalizeNewlines,
  readCanonicalTypesFile,
  repoRoot,
  writeCanonicalTypesFile,
  assertDatabaseUpToDate
};
